steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --runtime=python310
      - --source=data-loader-bq/src
      - --entry-point=main
      - --trigger-topic=${_PUBSUB_TOPIC}
      - --set-env-vars=ENV=${_ENVIRONMENT}
      - --set-env-vars=BQ_PROJECT=${_PROJECT_ID}
      - --set-env-vars=BQ_DATASET=${_BQ_DATASET}

options:
  dynamicSubstitutions: true

substitutions:
  _ENVIRONMENT: "" # Override with Cloud Build
  _SERVICE_ACCOUNT: ""  # Override with Cloud Build
  _PUBSUB_TOPIC: "" # Override with Cloud Build
  _USER_TABLE: "" # Override with Cloud Build
  _BQ_DATASET: "" # Override with Cloud Build
  _FUNCTION_NAME: data-loader-bq-${_ENVIRONMENT}
  _PROJECT_ID: "edts-playpen-leonardi"
  _REGION: "asia-southeast2"
