steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --region=${_REGION}
      - --runtime=python310
      - --source=data-loader-bq/src
      - --entry-point=main
      - --trigger-topic=${_PUBSUB_TOPIC}
      - --set-env-vars=ENV=${_ENVIRONMENT}
      - --set-env-vars=BQ_PROJECT=${_PROJECT_ID}
      - --set-env-vars=USER_TABLE=${_USER_TABLE}
      - --set-env-vars=PRINCIPAL_TIER_TABLE=${_PRINCIPAL_TIER_TABLE}

options:
  dynamicSubstitutions: true

substitutions:
  _ENVIRONMENT: '' # Override with Cloud Build
  _FUNCTION_NAME: data-loader-bq-${_ENVIRONMENT}
  _PROJECT_ID: "edts-playpen-leonardi"
  _REGION: "asia-southeast2"
  _PUBSUB_TOPIC: "test-customer-data"
  _USER_TABLE: "tmp.users"
  _PRINCIPAL_TIER_TABLE: "tmp.principle_tiers"
