steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --runtime=python310
      - --source=data-receiver-pubsub/src
      - --entry-point=main
      - --trigger-http
      - --set-env-vars=ENV=${_ENVIRONMENT}
      - --set-env-vars=PUBSUB_PROJECT=${_PROJECT_ID}
      - --set-env-vars=PUBSUB_TOPIC=${_PUBSUB_TOPIC}

options:
  dynamicSubstitutions: true

substitutions:
  _ENVIRONMENT: "" # Override with Cloud Build
  _SERVICE_ACCOUNT: ""  # Override with Cloud Build
  _PUBSUB_TOPIC: "" # Override with Cloud Build
  _FUNCTION_NAME: data-receiver-pubsub-${_ENVIRONMENT}
  _PROJECT_ID: "edts-playpen-leonardi"
  _REGION: "asia-southeast2"
